// Fantasy-themed word bank
export const wordBank = [
    { word: "DRAGON", clue: "A mythical creature that breathes fire" },
    { word: "WIZARD", clue: "A magical practitioner, often with a staff" },
    { word: "SPELL", clue: "A magical incantation" },
    { word: "SWORD", clue: "A weapon forged for battle" },
    { word: "CASTLE", clue: "A fortified home for royalty or wizards" },
    { word: "ELF", clue: "A magical creature with pointed ears" },
    { word: "MYSTIC", clue: "Someone who delves into the arcane arts" },
    { word: "POTION", clue: "A magical brew with healing or harmful effects" },
    { word: "RUNES", clue: "Magical symbols carved in stone or metal" },
    { word: "QUEST", clue: "An epic journey to achieve a goal" },
    { word: "SORCERER", clue: "A powerful wielder of arcane magic" },
    { word: "GOBLIN", clue: "A mischievous and greedy creature" },
    { word: "TROLL", clue: "A large, brutish creature dwelling under bridges" },
    { word: "ENCHANTED", clue: "Magically imbued with special properties" },
    { word: "UNICORN", clue: "A magical horse with a single horn" },
    { word: "PHOENIX", clue: "A bird that rises from its own ashes" },
    { word: "GRIFFIN", clue: "A mythical creature with the body of a lion and head of an eagle" },
    { word: "FAERIE", clue: "A small, magical being with wings" },
    { word: "NECROMANCER", clue: "A sorcerer who raises the dead" },
    { word: "DWARF", clue: "A short, sturdy creature skilled in mining and crafting" },
    { word: "ARMOR", clue: "Protective gear worn by warriors" },
    { word: "BARD", clue: "A storyteller or musician with magical songs" },
    { word: "SHIELD", clue: "A defensive tool to block attacks" },
    { word: "MAGIC", clue: "The art of producing supernatural effects" },
    { word: "FIREBALL", clue: "A destructive magical attack" },
    { word: "PORTAL", clue: "A magical doorway to another realm" },
    { word: "CROWN", clue: "A headpiece worn by royalty" },
    { word: "KINGDOM", clue: "A realm ruled by a monarch" },
    { word: "RUNESTONE", clue: "An inscribed stone used for magic" },
    { word: "CAULDRON", clue: "A large pot used for brewing potions" },
    { word: "SPELLBOOK", clue: "A book containing magical incantations" },
    { word: "FORTRESS", clue: "A heavily fortified building" },
    { word: "ARCHER", clue: "A skilled bowman in combat" },
    { word: "WARLOCK", clue: "A male witch or sorcerer" },
    { word: "PALADIN", clue: "A holy knight with divine powers" },
    { word: "RAVEN", clue: "A bird often associated with mystery and magic" },
    { word: "THRONE", clue: "A seat of power for a ruler" },
    { word: "BEAST", clue: "A wild or mythical animal" },
    { word: "CENTAUR", clue: "A creature with the upper body of a human and lower body of a horse" },
    { word: "BLADE", clue: "A sharp-edged weapon" },
    { word: "LANTERN", clue: "A light source for exploring dark areas" },
    { word: "MAP", clue: "A tool used to navigate realms" },
    { word: "WAND", clue: "A magical tool used to cast spells" },
    { word: "WEREWOLF", clue: "A human who transforms into a wolf during a full moon" },
    { word: "CHIMERA", clue: "A creature with parts from various animals" },
    { word: "SCROLL", clue: "A roll of parchment containing magical writings" },
    { word: "VAMPIRE", clue: "A blood-drinking creature of the night" },
    { word: "COVEN", clue: "A gathering of witches" },
    { word: "HERO", clue: "The protagonist of an epic tale" },
    { word: "RUNE", clue: "A single magical symbol" },
    { word: "KEY", clue: "An item used to unlock doors or chests" },
    { word: "TREASURE", clue: "A valuable hoard of gold and jewels" },
    { word: "ORB", clue: "A mystical spherical object" },
    { word: "DRUID", clue: "A nature-based spellcaster" },
    { word: "GENIE", clue: "A magical being that grants wishes" },
    { word: "WYVERN", clue: "A dragon-like creature with two legs and wings" },
    { word: "TALISMAN", clue: "An object believed to have magical properties" },
];

if (!wordBank || wordBank.length === 0) {
    console.error("Error: Word bank is not loaded or empty!");
} else {
    console.log(`${wordBank.length} words in the fantasy word bank loaded. Sample: ${wordBank.slice(0, 3).map(w => w.word).join(", ")}`);
}
